/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface AcquisitionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acquisitionIds"
      | "acquisitions"
      | "addAuthority"
      | "addVerifier"
      | "admin"
      | "approveAcquisition"
      | "authorities"
      | "getAcquisition"
      | "getAcquisitionCount"
      | "landRegistry"
      | "rejectAcquisition"
      | "removeAuthority"
      | "removeVerifier"
      | "requestAcquisition"
      | "transferOwnership"
      | "verifiers"
      | "verifyLand"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AcquisitionApproved"
      | "AcquisitionRejected"
      | "AcquisitionRequested"
      | "LandVerified"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acquisitionIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "acquisitions",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "addAuthority",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "approveAcquisition",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "authorities",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAcquisition",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAcquisitionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "landRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rejectAcquisition",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAuthority",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestAcquisition",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifiers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyLand",
    values: [string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "acquisitionIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acquisitions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "approveAcquisition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorities",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAcquisition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAcquisitionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "landRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rejectAcquisition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestAcquisition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifiers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verifyLand", data: BytesLike): Result;
}

export namespace AcquisitionApprovedEvent {
  export type InputTuple = [
    landId: string,
    authority: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    landId: string,
    authority: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    landId: string;
    authority: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AcquisitionRejectedEvent {
  export type InputTuple = [
    landId: string,
    verifier: AddressLike,
    reason: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    landId: string,
    verifier: string,
    reason: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    landId: string;
    verifier: string;
    reason: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AcquisitionRequestedEvent {
  export type InputTuple = [
    landId: string,
    authority: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    landId: string,
    authority: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    landId: string;
    authority: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LandVerifiedEvent {
  export type InputTuple = [
    landId: string,
    verifier: AddressLike,
    notes: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    landId: string,
    verifier: string,
    notes: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    landId: string;
    verifier: string;
    notes: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [
    landId: string,
    previousOwner: AddressLike,
    newOwner: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    landId: string,
    previousOwner: string,
    newOwner: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    landId: string;
    previousOwner: string;
    newOwner: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Acquisition extends BaseContract {
  connect(runner?: ContractRunner | null): Acquisition;
  waitForDeployment(): Promise<this>;

  interface: AcquisitionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acquisitionIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  acquisitions: TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        boolean
      ] & {
        landId: string;
        authority: string;
        verifier: string;
        status: bigint;
        amount: bigint;
        notes: string;
        createdAt: bigint;
        updatedAt: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  addAuthority: TypedContractMethod<
    [_authority: AddressLike],
    [void],
    "nonpayable"
  >;

  addVerifier: TypedContractMethod<
    [_verifier: AddressLike],
    [void],
    "nonpayable"
  >;

  admin: TypedContractMethod<[], [string], "view">;

  approveAcquisition: TypedContractMethod<
    [_landId: string],
    [boolean],
    "nonpayable"
  >;

  authorities: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getAcquisition: TypedContractMethod<
    [_landId: string],
    [
      [string, string, bigint, bigint, string, bigint, bigint] & {
        authority: string;
        verifier: string;
        status: bigint;
        amount: bigint;
        notes: string;
        createdAt: bigint;
        updatedAt: bigint;
      }
    ],
    "view"
  >;

  getAcquisitionCount: TypedContractMethod<[], [bigint], "view">;

  landRegistry: TypedContractMethod<[], [string], "view">;

  rejectAcquisition: TypedContractMethod<
    [_landId: string, _reason: string],
    [boolean],
    "nonpayable"
  >;

  removeAuthority: TypedContractMethod<
    [_authority: AddressLike],
    [void],
    "nonpayable"
  >;

  removeVerifier: TypedContractMethod<
    [_verifier: AddressLike],
    [void],
    "nonpayable"
  >;

  requestAcquisition: TypedContractMethod<
    [_landId: string, _amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [_landId: string, _newOwner: AddressLike],
    [boolean],
    "nonpayable"
  >;

  verifiers: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  verifyLand: TypedContractMethod<
    [_landId: string, _notes: string],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acquisitionIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "acquisitions"
  ): TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        boolean
      ] & {
        landId: string;
        authority: string;
        verifier: string;
        status: bigint;
        amount: bigint;
        notes: string;
        createdAt: bigint;
        updatedAt: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "addAuthority"
  ): TypedContractMethod<[_authority: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addVerifier"
  ): TypedContractMethod<[_verifier: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "approveAcquisition"
  ): TypedContractMethod<[_landId: string], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "authorities"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getAcquisition"
  ): TypedContractMethod<
    [_landId: string],
    [
      [string, string, bigint, bigint, string, bigint, bigint] & {
        authority: string;
        verifier: string;
        status: bigint;
        amount: bigint;
        notes: string;
        createdAt: bigint;
        updatedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAcquisitionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "landRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rejectAcquisition"
  ): TypedContractMethod<
    [_landId: string, _reason: string],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeAuthority"
  ): TypedContractMethod<[_authority: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeVerifier"
  ): TypedContractMethod<[_verifier: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestAcquisition"
  ): TypedContractMethod<
    [_landId: string, _amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<
    [_landId: string, _newOwner: AddressLike],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifiers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifyLand"
  ): TypedContractMethod<
    [_landId: string, _notes: string],
    [boolean],
    "nonpayable"
  >;

  getEvent(
    key: "AcquisitionApproved"
  ): TypedContractEvent<
    AcquisitionApprovedEvent.InputTuple,
    AcquisitionApprovedEvent.OutputTuple,
    AcquisitionApprovedEvent.OutputObject
  >;
  getEvent(
    key: "AcquisitionRejected"
  ): TypedContractEvent<
    AcquisitionRejectedEvent.InputTuple,
    AcquisitionRejectedEvent.OutputTuple,
    AcquisitionRejectedEvent.OutputObject
  >;
  getEvent(
    key: "AcquisitionRequested"
  ): TypedContractEvent<
    AcquisitionRequestedEvent.InputTuple,
    AcquisitionRequestedEvent.OutputTuple,
    AcquisitionRequestedEvent.OutputObject
  >;
  getEvent(
    key: "LandVerified"
  ): TypedContractEvent<
    LandVerifiedEvent.InputTuple,
    LandVerifiedEvent.OutputTuple,
    LandVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "AcquisitionApproved(string,address,uint256)": TypedContractEvent<
      AcquisitionApprovedEvent.InputTuple,
      AcquisitionApprovedEvent.OutputTuple,
      AcquisitionApprovedEvent.OutputObject
    >;
    AcquisitionApproved: TypedContractEvent<
      AcquisitionApprovedEvent.InputTuple,
      AcquisitionApprovedEvent.OutputTuple,
      AcquisitionApprovedEvent.OutputObject
    >;

    "AcquisitionRejected(string,address,string,uint256)": TypedContractEvent<
      AcquisitionRejectedEvent.InputTuple,
      AcquisitionRejectedEvent.OutputTuple,
      AcquisitionRejectedEvent.OutputObject
    >;
    AcquisitionRejected: TypedContractEvent<
      AcquisitionRejectedEvent.InputTuple,
      AcquisitionRejectedEvent.OutputTuple,
      AcquisitionRejectedEvent.OutputObject
    >;

    "AcquisitionRequested(string,address,uint256,uint256)": TypedContractEvent<
      AcquisitionRequestedEvent.InputTuple,
      AcquisitionRequestedEvent.OutputTuple,
      AcquisitionRequestedEvent.OutputObject
    >;
    AcquisitionRequested: TypedContractEvent<
      AcquisitionRequestedEvent.InputTuple,
      AcquisitionRequestedEvent.OutputTuple,
      AcquisitionRequestedEvent.OutputObject
    >;

    "LandVerified(string,address,string,uint256)": TypedContractEvent<
      LandVerifiedEvent.InputTuple,
      LandVerifiedEvent.OutputTuple,
      LandVerifiedEvent.OutputObject
    >;
    LandVerified: TypedContractEvent<
      LandVerifiedEvent.InputTuple,
      LandVerifiedEvent.OutputTuple,
      LandVerifiedEvent.OutputObject
    >;

    "OwnershipTransferred(string,address,address,uint256)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
