/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface EscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "getBalance"
      | "getPayment"
      | "lockFunds"
      | "paymentIds"
      | "payments"
      | "refundFunds"
      | "releaseFunds"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "FundsLocked" | "FundsRefunded" | "FundsReleased"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getPayment", values: [string]): string;
  encodeFunctionData(
    functionFragment: "lockFunds",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "paymentIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "payments", values: [string]): string;
  encodeFunctionData(functionFragment: "refundFunds", values: [string]): string;
  encodeFunctionData(
    functionFragment: "releaseFunds",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getPayment", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lockFunds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paymentIds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payments", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "refundFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseFunds",
    data: BytesLike
  ): Result;
}

export namespace FundsLockedEvent {
  export type InputTuple = [
    landId: string,
    authority: AddressLike,
    landOwner: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    landId: string,
    authority: string,
    landOwner: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    landId: string;
    authority: string;
    landOwner: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsRefundedEvent {
  export type InputTuple = [
    landId: string,
    authority: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    landId: string,
    authority: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    landId: string;
    authority: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsReleasedEvent {
  export type InputTuple = [
    landId: string,
    landOwner: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    landId: string,
    landOwner: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    landId: string;
    landOwner: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Escrow extends BaseContract {
  connect(runner?: ContractRunner | null): Escrow;
  waitForDeployment(): Promise<this>;

  interface: EscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  getBalance: TypedContractMethod<[], [bigint], "view">;

  getPayment: TypedContractMethod<
    [_landId: string],
    [
      [string, string, bigint, bigint, bigint, bigint] & {
        authority: string;
        landOwner: string;
        amount: bigint;
        status: bigint;
        lockedAt: bigint;
        releasedAt: bigint;
      }
    ],
    "view"
  >;

  lockFunds: TypedContractMethod<
    [_landId: string, _landOwner: AddressLike],
    [boolean],
    "payable"
  >;

  paymentIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  payments: TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, bigint, bigint, bigint, bigint, boolean] & {
        landId: string;
        authority: string;
        landOwner: string;
        amount: bigint;
        status: bigint;
        lockedAt: bigint;
        releasedAt: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  refundFunds: TypedContractMethod<[_landId: string], [boolean], "nonpayable">;

  releaseFunds: TypedContractMethod<[_landId: string], [boolean], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPayment"
  ): TypedContractMethod<
    [_landId: string],
    [
      [string, string, bigint, bigint, bigint, bigint] & {
        authority: string;
        landOwner: string;
        amount: bigint;
        status: bigint;
        lockedAt: bigint;
        releasedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "lockFunds"
  ): TypedContractMethod<
    [_landId: string, _landOwner: AddressLike],
    [boolean],
    "payable"
  >;
  getFunction(
    nameOrSignature: "paymentIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "payments"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, bigint, bigint, bigint, bigint, boolean] & {
        landId: string;
        authority: string;
        landOwner: string;
        amount: bigint;
        status: bigint;
        lockedAt: bigint;
        releasedAt: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "refundFunds"
  ): TypedContractMethod<[_landId: string], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "releaseFunds"
  ): TypedContractMethod<[_landId: string], [boolean], "nonpayable">;

  getEvent(
    key: "FundsLocked"
  ): TypedContractEvent<
    FundsLockedEvent.InputTuple,
    FundsLockedEvent.OutputTuple,
    FundsLockedEvent.OutputObject
  >;
  getEvent(
    key: "FundsRefunded"
  ): TypedContractEvent<
    FundsRefundedEvent.InputTuple,
    FundsRefundedEvent.OutputTuple,
    FundsRefundedEvent.OutputObject
  >;
  getEvent(
    key: "FundsReleased"
  ): TypedContractEvent<
    FundsReleasedEvent.InputTuple,
    FundsReleasedEvent.OutputTuple,
    FundsReleasedEvent.OutputObject
  >;

  filters: {
    "FundsLocked(string,address,address,uint256,uint256)": TypedContractEvent<
      FundsLockedEvent.InputTuple,
      FundsLockedEvent.OutputTuple,
      FundsLockedEvent.OutputObject
    >;
    FundsLocked: TypedContractEvent<
      FundsLockedEvent.InputTuple,
      FundsLockedEvent.OutputTuple,
      FundsLockedEvent.OutputObject
    >;

    "FundsRefunded(string,address,uint256,uint256)": TypedContractEvent<
      FundsRefundedEvent.InputTuple,
      FundsRefundedEvent.OutputTuple,
      FundsRefundedEvent.OutputObject
    >;
    FundsRefunded: TypedContractEvent<
      FundsRefundedEvent.InputTuple,
      FundsRefundedEvent.OutputTuple,
      FundsRefundedEvent.OutputObject
    >;

    "FundsReleased(string,address,uint256,uint256)": TypedContractEvent<
      FundsReleasedEvent.InputTuple,
      FundsReleasedEvent.OutputTuple,
      FundsReleasedEvent.OutputObject
    >;
    FundsReleased: TypedContractEvent<
      FundsReleasedEvent.InputTuple,
      FundsReleasedEvent.OutputTuple,
      FundsReleasedEvent.OutputObject
    >;
  };
}
