/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface LandRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "getLand"
      | "getLandCount"
      | "landIds"
      | "lands"
      | "registerLand"
      | "transferOwnership"
      | "updateDocumentHash"
      | "updateLandStatus"
      | "verifyDocumentHash"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DocumentHashUpdated"
      | "LandOwnershipTransferred"
      | "LandRegistered"
      | "LandStatusUpdated"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(functionFragment: "getLand", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getLandCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "landIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "lands", values: [string]): string;
  encodeFunctionData(
    functionFragment: "registerLand",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateDocumentHash",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateLandStatus",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyDocumentHash",
    values: [string, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getLand", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLandCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "landIds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lands", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerLand",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateDocumentHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateLandStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyDocumentHash",
    data: BytesLike
  ): Result;
}

export namespace DocumentHashUpdatedEvent {
  export type InputTuple = [
    landId: string,
    oldHash: BytesLike,
    newHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    landId: string,
    oldHash: string,
    newHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    landId: string;
    oldHash: string;
    newHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LandOwnershipTransferredEvent {
  export type InputTuple = [
    landId: string,
    previousOwner: AddressLike,
    newOwner: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    landId: string,
    previousOwner: string,
    newOwner: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    landId: string;
    previousOwner: string;
    newOwner: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LandRegisteredEvent {
  export type InputTuple = [
    landId: string,
    owner: AddressLike,
    documentHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    landId: string,
    owner: string,
    documentHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    landId: string;
    owner: string;
    documentHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LandStatusUpdatedEvent {
  export type InputTuple = [
    landId: string,
    oldStatus: BigNumberish,
    newStatus: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    landId: string,
    oldStatus: bigint,
    newStatus: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    landId: string;
    oldStatus: bigint;
    newStatus: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LandRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): LandRegistry;
  waitForDeployment(): Promise<this>;

  interface: LandRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  getLand: TypedContractMethod<
    [_landId: string],
    [
      [string, string, bigint, string, bigint] & {
        landId: string;
        owner: string;
        status: bigint;
        documentHash: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getLandCount: TypedContractMethod<[], [bigint], "view">;

  landIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  lands: TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, string, bigint, boolean] & {
        landId: string;
        owner: string;
        status: bigint;
        documentHash: string;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  registerLand: TypedContractMethod<
    [_landId: string, _documentHash: BytesLike],
    [boolean],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [_landId: string, _newOwner: AddressLike],
    [boolean],
    "nonpayable"
  >;

  updateDocumentHash: TypedContractMethod<
    [_landId: string, _newHash: BytesLike],
    [boolean],
    "nonpayable"
  >;

  updateLandStatus: TypedContractMethod<
    [_landId: string, _newStatus: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  verifyDocumentHash: TypedContractMethod<
    [_landId: string, _hash: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getLand"
  ): TypedContractMethod<
    [_landId: string],
    [
      [string, string, bigint, string, bigint] & {
        landId: string;
        owner: string;
        status: bigint;
        documentHash: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLandCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "landIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "lands"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, string, bigint, boolean] & {
        landId: string;
        owner: string;
        status: bigint;
        documentHash: string;
        timestamp: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerLand"
  ): TypedContractMethod<
    [_landId: string, _documentHash: BytesLike],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<
    [_landId: string, _newOwner: AddressLike],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateDocumentHash"
  ): TypedContractMethod<
    [_landId: string, _newHash: BytesLike],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateLandStatus"
  ): TypedContractMethod<
    [_landId: string, _newStatus: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyDocumentHash"
  ): TypedContractMethod<
    [_landId: string, _hash: BytesLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "DocumentHashUpdated"
  ): TypedContractEvent<
    DocumentHashUpdatedEvent.InputTuple,
    DocumentHashUpdatedEvent.OutputTuple,
    DocumentHashUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "LandOwnershipTransferred"
  ): TypedContractEvent<
    LandOwnershipTransferredEvent.InputTuple,
    LandOwnershipTransferredEvent.OutputTuple,
    LandOwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "LandRegistered"
  ): TypedContractEvent<
    LandRegisteredEvent.InputTuple,
    LandRegisteredEvent.OutputTuple,
    LandRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "LandStatusUpdated"
  ): TypedContractEvent<
    LandStatusUpdatedEvent.InputTuple,
    LandStatusUpdatedEvent.OutputTuple,
    LandStatusUpdatedEvent.OutputObject
  >;

  filters: {
    "DocumentHashUpdated(string,bytes32,bytes32,uint256)": TypedContractEvent<
      DocumentHashUpdatedEvent.InputTuple,
      DocumentHashUpdatedEvent.OutputTuple,
      DocumentHashUpdatedEvent.OutputObject
    >;
    DocumentHashUpdated: TypedContractEvent<
      DocumentHashUpdatedEvent.InputTuple,
      DocumentHashUpdatedEvent.OutputTuple,
      DocumentHashUpdatedEvent.OutputObject
    >;

    "LandOwnershipTransferred(string,address,address,uint256)": TypedContractEvent<
      LandOwnershipTransferredEvent.InputTuple,
      LandOwnershipTransferredEvent.OutputTuple,
      LandOwnershipTransferredEvent.OutputObject
    >;
    LandOwnershipTransferred: TypedContractEvent<
      LandOwnershipTransferredEvent.InputTuple,
      LandOwnershipTransferredEvent.OutputTuple,
      LandOwnershipTransferredEvent.OutputObject
    >;

    "LandRegistered(string,address,bytes32,uint256)": TypedContractEvent<
      LandRegisteredEvent.InputTuple,
      LandRegisteredEvent.OutputTuple,
      LandRegisteredEvent.OutputObject
    >;
    LandRegistered: TypedContractEvent<
      LandRegisteredEvent.InputTuple,
      LandRegisteredEvent.OutputTuple,
      LandRegisteredEvent.OutputObject
    >;

    "LandStatusUpdated(string,uint8,uint8,uint256)": TypedContractEvent<
      LandStatusUpdatedEvent.InputTuple,
      LandStatusUpdatedEvent.OutputTuple,
      LandStatusUpdatedEvent.OutputObject
    >;
    LandStatusUpdated: TypedContractEvent<
      LandStatusUpdatedEvent.InputTuple,
      LandStatusUpdatedEvent.OutputTuple,
      LandStatusUpdatedEvent.OutputObject
    >;
  };
}
